#!/usr/bin/env bash
#
# Open a pull request carrying today's brief into the publication repo.
#
# A PR rather than a direct push, deliberately. notitia-civica's own
# methodology/editorial-standard.md puts editorial responsibility with a human;
# auto-pushing generated output into the publication surface would contradict
# it. The gate upstream of this script decides whether a brief is *real*; a
# person still decides whether it is *publishable*.
#
# Required env:
#   GH_TOKEN    — token with contents:write and pull_requests:write on the
#                 publication repo
#   BRIEF_PATH  — path to the dated brief in this checkout
#   BRIEF_DATE  — YYYY-MM-DD, parsed from the brief filename
#
# Optional env:
#   PUBLICATION_REPO — defaults to CLS-1000/notitia-civica

set -euo pipefail

PUBLICATION_REPO="${PUBLICATION_REPO:-CLS-1000/notitia-civica}"
BASE_BRANCH="${BASE_BRANCH:-main}"
WORKDIR="$(mktemp -d)"
BRANCH="brief/${BRIEF_DATE}"
# Captured before any cd — everything read from the engine side resolves
# against this, not against whatever the working directory happens to be.
ENGINE_ROOT="$PWD"

for var in GH_TOKEN BRIEF_PATH BRIEF_DATE; do
  if [ -z "${!var:-}" ]; then
    echo "::error::$var is not set"
    exit 1
  fi
done

if [ ! -f "$BRIEF_PATH" ]; then
  echo "::error::brief not found at $BRIEF_PATH"
  exit 1
fi

echo "Publishing $BRIEF_PATH to $PUBLICATION_REPO on branch $BRANCH"

# --branch is explicit on purpose. Cloning without it trusts the remote's
# default HEAD; if that ever resolves to something other than the base branch
# the checkout comes up without briefs/, and the "append" to the append-only
# brief_index.jsonl silently becomes a fresh file that drops every prior entry.
git clone --depth 1 --branch "$BASE_BRANCH" \
  "https://x-access-token:${GH_TOKEN}@github.com/${PUBLICATION_REPO}.git" \
  "$WORKDIR/publication"
cd "$WORKDIR/publication"

if [ ! -d briefs ]; then
  echo "::error::$PUBLICATION_REPO@$BASE_BRANCH has no briefs/ directory — refusing to publish into an unexpected tree"
  exit 1
fi

# An existing branch means today's brief was already proposed — a re-run
# should be a no-op, not a second PR.
if git ls-remote --exit-code --heads origin "$BRANCH" >/dev/null 2>&1; then
  echo "::notice::$BRANCH already exists on $PUBLICATION_REPO — nothing to do"
  exit 0
fi

git config user.name "spec-1 cycle"
git config user.email "spec1_ops@proton.me"
git checkout -b "$BRANCH"

mkdir -p briefs
cp "$ENGINE_ROOT/$BRIEF_PATH" "briefs/spec1_brief_${BRIEF_DATE}.md"
cp "$ENGINE_ROOT/$BRIEF_PATH" "briefs/spec1_brief_latest.md"

# Carry over the prompts document when the cycle produced one.
PROMPTS="$ENGINE_ROOT/briefs/spec1_prompts_${BRIEF_DATE}.md"
if [ -f "$PROMPTS" ]; then
  cp "$PROMPTS" "briefs/spec1_prompts_${BRIEF_DATE}.md"
fi

# brief_index.jsonl is append-only. Take only this date's entries from the
# engine's index so the publication index is never rewritten or clobbered.
if [ -f "$ENGINE_ROOT/briefs/brief_index.jsonl" ]; then
  grep "\"date\": \"${BRIEF_DATE}\"" "$ENGINE_ROOT/briefs/brief_index.jsonl" \
    >> briefs/brief_index.jsonl || true
fi

if [ -z "$(git status --porcelain)" ]; then
  echo "::notice::brief is identical to what is already published — nothing to do"
  exit 0
fi

WORD_COUNT="$(wc -w < "briefs/spec1_brief_${BRIEF_DATE}.md" | tr -d ' ')"

git add briefs/
git commit -m "brief: SPEC-1 daily brief ${BRIEF_DATE}

Generated by the SPEC-1 daily cycle and passed the publishable-brief gate
(${WORD_COUNT} words). Editorial review still required before publication."

git push -u origin "$BRANCH"

PR_URL="$(GH_TOKEN="$GH_TOKEN" gh pr create \
  --repo "$PUBLICATION_REPO" \
  --base "$BASE_BRANCH" \
  --head "$BRANCH" \
  --title "Brief: SPEC-1 daily brief ${BRIEF_DATE}" \
  --body "Automated from the SPEC-1 daily cycle.

- **Date:** ${BRIEF_DATE}
- **Length:** ${WORD_COUNT} words
- **Gate:** passed \`check_brief_publishable.py\` — not a fallback stub, within the plausible length band for \`MAX_TOKENS\`

The gate only establishes that a brief was actually generated. It makes no
judgement about the content. Editorial review is still required before this is
published, per \`methodology/editorial-standard.md\`.

---
_Generated by [Claude Code](https://claude.ai/code)_")"

echo "::notice::opened $PR_URL"
